//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magensa.DafV4.Services
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessCardSwipeRequest", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessCardSwipeRequest : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessCardSwipeRequestDataField;
        
        private Magensa.DafV4.Services.Authentication AuthenticationField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.DafV4.Services.ProcessCardSwipeInput[] ProcessCardSwipeInputsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessCardSwipeRequestData
        {
            get
            {
                return this.AdditionalProcessCardSwipeRequestDataField;
            }
            set
            {
                this.AdditionalProcessCardSwipeRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DafV4.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.ProcessCardSwipeInput[] ProcessCardSwipeInputs
        {
            get
            {
                return this.ProcessCardSwipeInputsField;
            }
            set
            {
                this.ProcessCardSwipeInputsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class Authentication : object
    {
        
        private string CustomerCodeField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessCardSwipeInput", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessCardSwipeInput : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private Magensa.DafV4.Services.Authentication AuthenticationField;
        
        private string BillingLabelField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.DafV4.Services.EncryptedCardSwipe EncryptedCardSwipeField;
        
        private Magensa.DafV4.Services.PayloadInfo PayloadInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DafV4.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingLabel
        {
            get
            {
                return this.BillingLabelField;
            }
            set
            {
                this.BillingLabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.EncryptedCardSwipe EncryptedCardSwipe
        {
            get
            {
                return this.EncryptedCardSwipeField;
            }
            set
            {
                this.EncryptedCardSwipeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DafV4.Services.PayloadInfo PayloadInfo
        {
            get
            {
                return this.PayloadInfoField;
            }
            set
            {
                this.PayloadInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncryptedCardSwipe", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class EncryptedCardSwipe : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalEncryptedCardSwipeDataField;
        
        private string DeviceSNField;
        
        private System.Nullable<bool> IsReturnCardIDField;
        
        private string KSNField;
        
        private string MagnePrintField;
        
        private string MagnePrintStatusField;
        
        private string Track1Field;
        
        private string Track2Field;
        
        private string Track3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalEncryptedCardSwipeData
        {
            get
            {
                return this.AdditionalEncryptedCardSwipeDataField;
            }
            set
            {
                this.AdditionalEncryptedCardSwipeDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceSN
        {
            get
            {
                return this.DeviceSNField;
            }
            set
            {
                this.DeviceSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsReturnCardID
        {
            get
            {
                return this.IsReturnCardIDField;
            }
            set
            {
                this.IsReturnCardIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagnePrint
        {
            get
            {
                return this.MagnePrintField;
            }
            set
            {
                this.MagnePrintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagnePrintStatus
        {
            get
            {
                return this.MagnePrintStatusField;
            }
            set
            {
                this.MagnePrintStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track1
        {
            get
            {
                return this.Track1Field;
            }
            set
            {
                this.Track1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track2
        {
            get
            {
                return this.Track2Field;
            }
            set
            {
                this.Track2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track3
        {
            get
            {
                return this.Track3Field;
            }
            set
            {
                this.Track3Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayloadInfo", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class PayloadInfo : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalPayloadInfoDataField;
        
        private string Base64ClientCertField;
        
        private string ClientCertPasswordField;
        
        private Magensa.DafV4.Services.HTTPInfo HTTPInfoField;
        
        private System.Nullable<Magensa.DafV4.Services.NetworkProtocolType> NetworkProtocolTypeField;
        
        private string PayloadField;
        
        private Magensa.DafV4.Services.TCPIPInfo TCPIPInfoField;
        
        private string UriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalPayloadInfoData
        {
            get
            {
                return this.AdditionalPayloadInfoDataField;
            }
            set
            {
                this.AdditionalPayloadInfoDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base64ClientCert
        {
            get
            {
                return this.Base64ClientCertField;
            }
            set
            {
                this.Base64ClientCertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCertPassword
        {
            get
            {
                return this.ClientCertPasswordField;
            }
            set
            {
                this.ClientCertPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.HTTPInfo HTTPInfo
        {
            get
            {
                return this.HTTPInfoField;
            }
            set
            {
                this.HTTPInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Magensa.DafV4.Services.NetworkProtocolType> NetworkProtocolType
        {
            get
            {
                return this.NetworkProtocolTypeField;
            }
            set
            {
                this.NetworkProtocolTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Payload
        {
            get
            {
                return this.PayloadField;
            }
            set
            {
                this.PayloadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.TCPIPInfo TCPIPInfo
        {
            get
            {
                return this.TCPIPInfoField;
            }
            set
            {
                this.TCPIPInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Uri
        {
            get
            {
                return this.UriField;
            }
            set
            {
                this.UriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HTTPInfo", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class HTTPInfo : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalHTTPInfoDataField;
        
        private System.Collections.Generic.KeyValuePair<string, string>[] HeadersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalHTTPInfoData
        {
            get
            {
                return this.AdditionalHTTPInfoDataField;
            }
            set
            {
                this.AdditionalHTTPInfoDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] Headers
        {
            get
            {
                return this.HeadersField;
            }
            set
            {
                this.HeadersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCPIPInfo", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class TCPIPInfo : object
    {
        
        private byte[] AccessEngineHeaderHexField;
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalTCPIPInfoDataField;
        
        private System.Nullable<int> NumberOfBytesToAddForLengthField;
        
        private int PortField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] AccessEngineHeaderHex
        {
            get
            {
                return this.AccessEngineHeaderHexField;
            }
            set
            {
                this.AccessEngineHeaderHexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalTCPIPInfoData
        {
            get
            {
                return this.AdditionalTCPIPInfoDataField;
            }
            set
            {
                this.AdditionalTCPIPInfoDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfBytesToAddForLength
        {
            get
            {
                return this.NumberOfBytesToAddForLengthField;
            }
            set
            {
                this.NumberOfBytesToAddForLengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port
        {
            get
            {
                return this.PortField;
            }
            set
            {
                this.PortField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NetworkProtocolType", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public enum NetworkProtocolType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HTTP = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TCPIP = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessCardSwipeResponse", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessCardSwipeResponse : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessCardSwipeResponseDataField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.DafV4.Services.ProcessCardSwipeOutput[] ProcessCardSwipeOutputsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessCardSwipeResponseData
        {
            get
            {
                return this.AdditionalProcessCardSwipeResponseDataField;
            }
            set
            {
                this.AdditionalProcessCardSwipeResponseDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.ProcessCardSwipeOutput[] ProcessCardSwipeOutputs
        {
            get
            {
                return this.ProcessCardSwipeOutputsField;
            }
            set
            {
                this.ProcessCardSwipeOutputsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessCardSwipeOutput", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessCardSwipeOutput : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessCardSwipeResponseDataField;
        
        private Magensa.DafV4.Services.CardSwipeOutput CardSwipeOutputField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.DafV4.Services.DecryptForwardFaultException DecryptForwardFaultExceptionField;
        
        private string MagTranIDField;
        
        private string PayloadResponseField;
        
        private string PayloadTokenField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessCardSwipeResponseData
        {
            get
            {
                return this.AdditionalProcessCardSwipeResponseDataField;
            }
            set
            {
                this.AdditionalProcessCardSwipeResponseDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.CardSwipeOutput CardSwipeOutput
        {
            get
            {
                return this.CardSwipeOutputField;
            }
            set
            {
                this.CardSwipeOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.DecryptForwardFaultException DecryptForwardFaultException
        {
            get
            {
                return this.DecryptForwardFaultExceptionField;
            }
            set
            {
                this.DecryptForwardFaultExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadResponse
        {
            get
            {
                return this.PayloadResponseField;
            }
            set
            {
                this.PayloadResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadToken
        {
            get
            {
                return this.PayloadTokenField;
            }
            set
            {
                this.PayloadTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardSwipeOutput", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class CardSwipeOutput : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private string CardIDField;
        
        private System.Nullable<bool> IsReplayField;
        
        private System.Nullable<decimal> MagnePrintScoreField;
        
        private string PanLast4Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardID
        {
            get
            {
                return this.CardIDField;
            }
            set
            {
                this.CardIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsReplay
        {
            get
            {
                return this.IsReplayField;
            }
            set
            {
                this.IsReplayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MagnePrintScore
        {
            get
            {
                return this.MagnePrintScoreField;
            }
            set
            {
                this.MagnePrintScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PanLast4
        {
            get
            {
                return this.PanLast4Field;
            }
            set
            {
                this.PanLast4Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecryptForwardFaultException", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class DecryptForwardFaultException : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalFaultDataField;
        
        private string CodeField;
        
        private string CustomerTransactionIDField;
        
        private string MagTranIDField;
        
        private string MessageField;
        
        private string PayloadTokenField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalFaultData
        {
            get
            {
                return this.AdditionalFaultDataField;
            }
            set
            {
                this.AdditionalFaultDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadToken
        {
            get
            {
                return this.PayloadTokenField;
            }
            set
            {
                this.PayloadTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecryptForwardFaultJSONFaultException", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class DecryptForwardFaultJSONFaultException : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalFaultDataField;
        
        private string CustomerTransactionIDField;
        
        private string FaultCodeField;
        
        private string FaultReasonField;
        
        private string MagTranIDField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalFaultData
        {
            get
            {
                return this.AdditionalFaultDataField;
            }
            set
            {
                this.AdditionalFaultDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultCode
        {
            get
            {
                return this.FaultCodeField;
            }
            set
            {
                this.FaultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultReason
        {
            get
            {
                return this.FaultReasonField;
            }
            set
            {
                this.FaultReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessDataRequest", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessDataRequest : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessDataRequestDataField;
        
        private Magensa.DafV4.Services.Authentication AuthenticationField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.DafV4.Services.ProcessDataInput[] ProcessDataInputsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessDataRequestData
        {
            get
            {
                return this.AdditionalProcessDataRequestDataField;
            }
            set
            {
                this.AdditionalProcessDataRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DafV4.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.ProcessDataInput[] ProcessDataInputs
        {
            get
            {
                return this.ProcessDataInputsField;
            }
            set
            {
                this.ProcessDataInputsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessDataInput", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessDataInput : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private Magensa.DafV4.Services.Authentication AuthenticationField;
        
        private string BillingLabelField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.DafV4.Services.DataInput DataInputField;
        
        private Magensa.DafV4.Services.PayloadInfo PayloadInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DafV4.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingLabel
        {
            get
            {
                return this.BillingLabelField;
            }
            set
            {
                this.BillingLabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.DataInput DataInput
        {
            get
            {
                return this.DataInputField;
            }
            set
            {
                this.DataInputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DafV4.Services.PayloadInfo PayloadInfo
        {
            get
            {
                return this.PayloadInfoField;
            }
            set
            {
                this.PayloadInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataInput", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class DataInput : object
    {
        
        private string DataField;
        
        private Magensa.DafV4.Services.FormatType DataFormatTypeField;
        
        private Magensa.DafV4.Services.EncryptionInfo EncryptionInfoField;
        
        private bool IsEncryptedField;
        
        private string OutputPanLast4FormatField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.FormatType DataFormatType
        {
            get
            {
                return this.DataFormatTypeField;
            }
            set
            {
                this.DataFormatTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.EncryptionInfo EncryptionInfo
        {
            get
            {
                return this.EncryptionInfoField;
            }
            set
            {
                this.EncryptionInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEncrypted
        {
            get
            {
                return this.IsEncryptedField;
            }
            set
            {
                this.IsEncryptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputPanLast4Format
        {
            get
            {
                return this.OutputPanLast4FormatField;
            }
            set
            {
                this.OutputPanLast4FormatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncryptionInfo", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class EncryptionInfo : object
    {
        
        private string EncryptionTypeField;
        
        private string KSNField;
        
        private int NumberOfPaddedBytesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EncryptionType
        {
            get
            {
                return this.EncryptionTypeField;
            }
            set
            {
                this.EncryptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPaddedBytes
        {
            get
            {
                return this.NumberOfPaddedBytesField;
            }
            set
            {
                this.NumberOfPaddedBytesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormatType", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public enum FormatType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TLV = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessDataResponse", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessDataResponse : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessDataResponseDataField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.DafV4.Services.ProcessDataOutput[] ProcessDataOutputsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessDataResponseData
        {
            get
            {
                return this.AdditionalProcessDataResponseDataField;
            }
            set
            {
                this.AdditionalProcessDataResponseDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.ProcessDataOutput[] ProcessDataOutputs
        {
            get
            {
                return this.ProcessDataOutputsField;
            }
            set
            {
                this.ProcessDataOutputsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessDataOutput", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessDataOutput : object
    {
        
        private string CustomerTransactionIDField;
        
        private Magensa.DafV4.Services.DataOutput DataOutputField;
        
        private Magensa.DafV4.Services.DecryptForwardFaultException DecryptForwardFaultExceptionField;
        
        private string MagTranIDField;
        
        private string PayloadResponseField;
        
        private string PayloadTokenField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.DataOutput DataOutput
        {
            get
            {
                return this.DataOutputField;
            }
            set
            {
                this.DataOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.DecryptForwardFaultException DecryptForwardFaultException
        {
            get
            {
                return this.DecryptForwardFaultExceptionField;
            }
            set
            {
                this.DecryptForwardFaultExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadResponse
        {
            get
            {
                return this.PayloadResponseField;
            }
            set
            {
                this.PayloadResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadToken
        {
            get
            {
                return this.PayloadTokenField;
            }
            set
            {
                this.PayloadTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataOutput", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class DataOutput : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private string CardIDField;
        
        private System.Nullable<bool> IsReplayField;
        
        private string PanLast4Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardID
        {
            get
            {
                return this.CardIDField;
            }
            set
            {
                this.CardIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsReplay
        {
            get
            {
                return this.IsReplayField;
            }
            set
            {
                this.IsReplayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PanLast4
        {
            get
            {
                return this.PanLast4Field;
            }
            set
            {
                this.PanLast4Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessTokenRequest", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessTokenRequest : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessTokenRequestDataField;
        
        private Magensa.DafV4.Services.Authentication AuthenticationField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.DafV4.Services.ProcessTokenInput[] ProcessTokenInputsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessTokenRequestData
        {
            get
            {
                return this.AdditionalProcessTokenRequestDataField;
            }
            set
            {
                this.AdditionalProcessTokenRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DafV4.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.ProcessTokenInput[] ProcessTokenInputs
        {
            get
            {
                return this.ProcessTokenInputsField;
            }
            set
            {
                this.ProcessTokenInputsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessTokenInput", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessTokenInput : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private Magensa.DafV4.Services.Authentication AuthenticationField;
        
        private string BillingLabelField;
        
        private string CustomerTransactionIDField;
        
        private string OutputPanLast4FormatField;
        
        private Magensa.DafV4.Services.PayloadInfo PayloadInfoField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DafV4.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingLabel
        {
            get
            {
                return this.BillingLabelField;
            }
            set
            {
                this.BillingLabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputPanLast4Format
        {
            get
            {
                return this.OutputPanLast4FormatField;
            }
            set
            {
                this.OutputPanLast4FormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.DafV4.Services.PayloadInfo PayloadInfo
        {
            get
            {
                return this.PayloadInfoField;
            }
            set
            {
                this.PayloadInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessTokenResponse", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessTokenResponse : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessTokenResponseDataField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.DafV4.Services.ProcessTokenOutput[] ProcessTokenOutputsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessTokenResponseData
        {
            get
            {
                return this.AdditionalProcessTokenResponseDataField;
            }
            set
            {
                this.AdditionalProcessTokenResponseDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.ProcessTokenOutput[] ProcessTokenOutputs
        {
            get
            {
                return this.ProcessTokenOutputsField;
            }
            set
            {
                this.ProcessTokenOutputsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessTokenOutput", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class ProcessTokenOutput : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessTokenResponseDataField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.DafV4.Services.DecryptForwardFaultException DecryptForwardFaultExceptionField;
        
        private string MagTranIDField;
        
        private string PayloadResponseField;
        
        private string PayloadTokenField;
        
        private Magensa.DafV4.Services.TokenOutput TokenOutputField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalProcessTokenResponseData
        {
            get
            {
                return this.AdditionalProcessTokenResponseDataField;
            }
            set
            {
                this.AdditionalProcessTokenResponseDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.DecryptForwardFaultException DecryptForwardFaultException
        {
            get
            {
                return this.DecryptForwardFaultExceptionField;
            }
            set
            {
                this.DecryptForwardFaultExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadResponse
        {
            get
            {
                return this.PayloadResponseField;
            }
            set
            {
                this.PayloadResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadToken
        {
            get
            {
                return this.PayloadTokenField;
            }
            set
            {
                this.PayloadTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.DafV4.Services.TokenOutput TokenOutput
        {
            get
            {
                return this.TokenOutputField;
            }
            set
            {
                this.TokenOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenOutput", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
    public partial class TokenOutput : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private string PanLast4Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PanLast4
        {
            get
            {
                return this.PanLast4Field;
            }
            set
            {
                this.PanLast4Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Magensa.DafV4.Services.IDecryptAndForward")]
    public interface IDecryptAndForward
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptAndForward/ProcessCardSwipe", ReplyAction="http://tempuri.org/IDecryptAndForward/ProcessCardSwipeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.DafV4.Services.DecryptForwardFaultException), Action="http://tempuri.org/IDecryptAndForward/ProcessCardSwipeDecryptForwardFaultExceptio" +
            "nFault", Name="DecryptForwardFaultException", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.DafV4.Services.DecryptForwardFaultJSONFaultException), Action="http://tempuri.org/IDecryptAndForward/ProcessCardSwipeDecryptForwardFaultJSONFaul" +
            "tExceptionFault", Name="DecryptForwardFaultJSONFaultException", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
        System.Threading.Tasks.Task<Magensa.DafV4.Services.ProcessCardSwipeResponse> ProcessCardSwipeAsync(Magensa.DafV4.Services.ProcessCardSwipeRequest ProcessCardSwipeRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptAndForward/ProcessData", ReplyAction="http://tempuri.org/IDecryptAndForward/ProcessDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.DafV4.Services.DecryptForwardFaultException), Action="http://tempuri.org/IDecryptAndForward/ProcessDataDecryptForwardFaultExceptionFaul" +
            "t", Name="DecryptForwardFaultException", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.DafV4.Services.DecryptForwardFaultJSONFaultException), Action="http://tempuri.org/IDecryptAndForward/ProcessDataDecryptForwardFaultJSONFaultExce" +
            "ptionFault", Name="DecryptForwardFaultJSONFaultException", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
        System.Threading.Tasks.Task<Magensa.DafV4.Services.ProcessDataResponse> ProcessDataAsync(Magensa.DafV4.Services.ProcessDataRequest ProcessDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptAndForward/ProcessToken", ReplyAction="http://tempuri.org/IDecryptAndForward/ProcessTokenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.DafV4.Services.DecryptForwardFaultException), Action="http://tempuri.org/IDecryptAndForward/ProcessTokenDecryptForwardFaultExceptionFau" +
            "lt", Name="DecryptForwardFaultException", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.DafV4.Services.DecryptForwardFaultJSONFaultException), Action="http://tempuri.org/IDecryptAndForward/ProcessTokenDecryptForwardFaultJSONFaultExc" +
            "eptionFault", Name="DecryptForwardFaultJSONFaultException", Namespace="http://schemas.datacontract.org/2004/07/DecryptAndForwardCoreNSV4")]
        System.Threading.Tasks.Task<Magensa.DafV4.Services.ProcessTokenResponse> ProcessTokenAsync(Magensa.DafV4.Services.ProcessTokenRequest httpPostInput);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IDecryptAndForwardChannel : Magensa.DafV4.Services.IDecryptAndForward, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DecryptAndForwardClient : System.ServiceModel.ClientBase<Magensa.DafV4.Services.IDecryptAndForward>, Magensa.DafV4.Services.IDecryptAndForward
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DecryptAndForwardClient() : 
                base(DecryptAndForwardClient.GetDefaultBinding(), DecryptAndForwardClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IDecryptAndForward.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DecryptAndForwardClient(EndpointConfiguration endpointConfiguration) : 
                base(DecryptAndForwardClient.GetBindingForEndpoint(endpointConfiguration), DecryptAndForwardClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DecryptAndForwardClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DecryptAndForwardClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DecryptAndForwardClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DecryptAndForwardClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DecryptAndForwardClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Magensa.DafV4.Services.ProcessCardSwipeResponse> ProcessCardSwipeAsync(Magensa.DafV4.Services.ProcessCardSwipeRequest ProcessCardSwipeRequest)
        {
            return base.Channel.ProcessCardSwipeAsync(ProcessCardSwipeRequest);
        }
        
        public System.Threading.Tasks.Task<Magensa.DafV4.Services.ProcessDataResponse> ProcessDataAsync(Magensa.DafV4.Services.ProcessDataRequest ProcessDataRequest)
        {
            return base.Channel.ProcessDataAsync(ProcessDataRequest);
        }
        
        public System.Threading.Tasks.Task<Magensa.DafV4.Services.ProcessTokenResponse> ProcessTokenAsync(Magensa.DafV4.Services.ProcessTokenRequest httpPostInput)
        {
            return base.Channel.ProcessTokenAsync(httpPostInput);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDecryptAndForward))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDecryptAndForward))
            {
                return new System.ServiceModel.EndpointAddress("https://svc1.magensa.net/DAFV4/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DecryptAndForwardClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IDecryptAndForward);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DecryptAndForwardClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IDecryptAndForward);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IDecryptAndForward,
        }
    }
}
